lvim.builtin.telescope.defaults.file_ignore_patterns = {
    ".git/",
    "target/",
    "docs/",
    "vendor/*",
    "%.lock",
    "__pycache__/*",
    "%.sqlite3",
    "%.ipynb",
    "node_modules/*",
    -- "%.jpg",
    -- "%.jpeg",
    -- "%.png",
    "%.svg",
    "%.otf",
    "%.ttf",
    "%.webp",
    ".dart_tool/",
    ".github/",
    ".gradle/",
    ".idea/",
    ".settings/",
    ".vscode/",
    "__pycache__/",
    "build/",
    "env/",
    "gradle/",
    "node_modules/",
    "%.pdb",
    "%.dll",
    "%.class",
    "%.exe",
    "%.cache",
    "%.ico",
    "%.pdf",
    "%.dylib",
    "%.jar",
    "%.docx",
    "%.met",
    "smalljre_*/*",
    ".vale/",
    "%.burp",
    "%.mp4",
    "%.mkv",
    "%.rar",
    "%.zip",
    "%.7z",
    "%.tar",
    "%.bz2",
    "%.epub",
    "%.flac",
    "%.tar.gz",
  }

lvim.builtin.telescope.extensions.undo = {
  use_delta = true,
  use_custom_command = nil, -- setting this implies `use_delta = false`. Accepted format is: { "bash", "-c", "echo '$DIFF' | delta" }
  side_by_side = false,
  diff_context_lines = vim.o.scrolloff,
  entry_format = "state #$ID, $STAT, $TIME",
  mappings = {
    i = {
      -- IMPORTANT: Note that telescope-undo must be available when telescope is configured if
      -- you want to replicate these defaults and use the following actions. This means
      -- installing as a dependency of telescope in it's `requirements` and loading this
      -- extension from there instead of having the separate plugin definition as outlined
      -- above.
      -- ["<cr>"] = require("telescope-undo.actions").yank_additions,
      -- ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
      -- ["<C-cr>"] = require("telescope-undo.actions").restore,
    },
  },
}
